# Configuracion de produccion (Docker)

app.engine.stockfish-path=${CHESS_ENGINE_PATH:/usr/bin/stockfish}

app.storage.books-path=${CHESS_DATA_PATH:/data}/books
app.storage.chess-path=${CHESS_DATA_PATH:/data}/chess

spring.datasource.url=jdbc:sqlite:${CHESS_DATA_PATH:/data}/users.db

app.vision.detector-url=${MS_BOARD_DETECTOR_URL:http://ms-board-detector:8001}
app.vision.segmenter-url=${MS_BOARD_SEGMENTER_URL:http://ms-board-segmenter:8002}
app.vision.classifier-url=${MS_PIECE_CLASSIFIER_URL:http://ms-piece-classifier:8003}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
