spring.application.name=backend

app.storage.books-path=./data/books
app.storage.chess-path=./data/chess

# Configuración de renderizado
app.render.default-dpi=150

# Límite de tamaño para importar PDFs
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.vision.detector-url=http://localhost:8003
app.vision.segmenter-url=http://localhost:8002
app.vision.classifier-url=http://localhost:8001

app.engine.stockfish-path=./engines/stockfish.exe


spring.datasource.url=jdbc:sqlite:./data/users.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false