spring.application.name=backend

app.storage.books-path=./data/books
app.storage.chess-path=./data/chess

# Configuración de renderizado
app.render.default-dpi=150

# Límite de tamaño para importar PDFs
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.vision.detector-url=http://localhost:8003
app.vision.segmenter-url=http://localhost:8002
app.vision.classifier-url=http://localhost:8001
